### ISSUE TITLE
FileNotFoundError: large_corpus.bel

### ISSUE THREAD

**Issue by remondulos** [sorgerlab/indra#638] opened 2018-09-25 08:57 UTC
When running the code below, we get a FileNotFoundError exception. 
It seems that Indra cannot find the large_corpus.bel file. I'm running Indra in Jupyter using an Anaconda environment. Could you please help?

```
from indra.tools.gene_network import GeneNetwork

gn = GeneNetwork(['TMEM173'])
bel_stmts = gn.get_bel_stmts()
```

**The complete error message is:**

INFO: [2018-09-25 10:50:26] indra/pybel.io.lines - Loading from path: C:\Users\dulosr\AppData\Roaming\Python\Python36\site-packages\indra\sources\bel\../../..\data\large_corpus.bel
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-99500a89dcd7> in <module>()
      3 gn = GeneNetwork(['TMEM173'])
      4 # biopax_stmts = gn.get_biopax_stmts()
----> 5 bel_stmts = gn.get_bel_stmts()

~\AppData\Roaming\Python\Python36\site-packages\indra\tools\gene_network.py in get_bel_stmts(self, filter)
     71         # No cache, so perform the queries
     72         else:
---> 73             bel_proc = bel.process_pybel_neighborhood(self.gene_list)
     74             bel_statements = bel_proc.statements
     75             # Save to pickle file if we're caching

~\AppData\Roaming\Python\Python36\site-packages\indra\sources\bel\bel_api.py in process_pybel_neighborhood(gene_names, network_file, network_type)
    104                                     'data', 'large_corpus.bel')
    105     if network_type == 'belscript':
--> 106         bp = process_belscript(network_file)
    107     elif network_type == 'json':
    108         bp = process_json_file(network_file)

~\AppData\Roaming\Python\Python36\site-packages\indra\sources\bel\bel_api.py in process_belscript(file_name, **kwargs)
    212     identifier_validation = kwargs.get('identifier_validation', False)
    213     kwargs['identifier_validation'] = identifier_validation
--> 214     pybel_graph = pybel.from_path(file_name, **kwargs)
    215     return process_pybel_graph(pybel_graph)
    216 

~\AppData\Local\Continuum\anaconda3\envs\Indra\lib\site-packages\pybel\io\lines.py in from_path(path, manager, allow_nested, citation_clearing, encoding, use_tqdm, disallow_unqualified_translocations, **kwargs)
     69     """
     70     log.info('Loading from path: %s', path)
---> 71     with codecs.open(os.path.expanduser(path), encoding=encoding) as file:
     72         return from_lines(
     73             lines=file,

~\AppData\Local\Continuum\anaconda3\envs\Indra\lib\codecs.py in open(filename, mode, encoding, errors, buffering)
    895         # Force opening of the file in binary mode
    896         mode = mode + 'b'
--> 897     file = builtins.open(filename, mode, buffering)
    898     if encoding is None:
    899         return file

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dulosr\\AppData\\Roaming\\Python\\Python36\\site-packages\\indra\\sources\\bel\\../../..\\data\\large_corpus.bel'

**Comment by pagreene** [comment] 2018-09-25 12:59
The problem is that you are running on Windows, actually. Note the `../../..` in the middle of the path. I will tweak it to be Windows compatible and merge it ASAP.

**Comment by bgyori** [comment] 2018-09-25 13:43
Hi @remondulos, unfortunately that file is not part of the installation. The easiest immediate solution is to clone indra from github as
```
git clone https://github.com/sorgerlab/indra.git
```
and make sure that it is visible on your PYTHONPATH so that you can import it. This will give you access to all the files in the `data` folder.

**Comment by pagreene** [comment] 2018-09-25 13:49
Cloning will also give you access to the latest changes, such as those that fix the file-path issue.

**Comment by bgyori** [comment] 2018-09-25 21:52
Did the approach to clone the repo or the updates we merged today resolve your issue?

**Comment by cthoyt** [comment] 2018-09-30 11:50
@pagreene after fixing the file path to be more compatible with windows, you could also check for the existence of the file and fall back to using PyBEL's from_url function to get and parse it (though this will be a quite a bit slower for users)

```python
import pybel

path = "https://arty.scai.fraunhofer.de/artifactory/bel/knowledge/large_corpus/large_corpus-20170611.bel"
graph = pybel.from_url(path, allow_nested=True, citation_clearing=False)
```

**Closed** 2018-10-03 15:32 UTC
